In [6]:
from create_patches import patch
import time
from matplotlib import pyplot as plt
import torch
import openslide as op
import numpy as np
import pyvips


In [7]:
from create_patches.filters.ClassificationFilter import ClassificationFilter
import sys
sys.path.append("..")
from oed_research_utils.utilities.ml.model_creation.src.models.VGGBinary import VGGBinary
from oed_research_utils.utilities.ml.model_creation.src.transforms.StandardizeTransform import StandardizeTransform

MASK_PATH = "../data/new_data/test_slides/ptest1_mask.tif"

model = VGGBinary(pretrained=False)
model.load_state_dict(torch.load("../data/new_data/model_weights/vgg_poster_run.pt"))

custom_filter = ClassificationFilter(MASK_PATH, model, StandardizeTransform()).filter

In [8]:
IMAGE_PATH = "../data/new_data/test_slides/ptest1.svs"
PATCH_PATH = "create_patches"
PATCH_SIZE = 512

patcher = patch.Patcher(PATCH_PATH, use_hdf5=True)# set up the patcher

patches, metadata = patcher.patch(IMAGE_PATH, PATCH_SIZE, overlap=None, level=1, return_patches=True, filter=custom_filter) # patcher patches the image and saves the patches to and hdf5 file at the path specified to the constuctor
# patcher.patch_with_mask(IMAGE_PATH, XML_PATH, PATCH_SIZE, level=0, return_patches=False, accept_threshold=10) #accept_threshold between 0 and 255

Patches file create_patches/patches.h5 already exists.  Will overwrite or append.


 67%|██████▋   | 2/3 [00:00<00:00,  4.27it/s]

0


100%|██████████| 3/3 [00:00<00:00,  3.87it/s]

0
0
0
0


In [9]:
rows = patcher.recombine_no_overlap(patches=patches, metadata=metadata, from_array=True)

Loading array patches
Beginning Recombination
New shape: (1536, 3072, 3)


In [6]:
print(rows.shape)

(1862, 3386, 3)


In [10]:
import pyvips
vi = pyvips.Image.new_from_array(rows)
vi.tiffsave("../data/new_data/test_slides/ptest1_output_test_512_lev1_110.tif", tile=True, depth="onetile", pyramid=True, compression="jpeg", bigtiff=False)

In [1]:
from create_patches import patch
import time
from matplotlib import pyplot as plt
import torch
import pyvips


IMAGE_PATH = "../data/new_data/test_images/test_1.svs"
PATCH_PATH = "create_patches"
PATCH_SIZE = 512


patcher = patch.Patcher(PATCH_PATH) # set up the patcher

patcher.patch(IMAGE_PATH, PATCH_SIZE) # patcher patches the image and saves the patches to and hdf5 file at the path specified to the constuctor

rows = patcher.recombine(IMAGE_PATH)

vi = pyvips.Image.new_from_array(rows)
vi.tiffsave("./normal.tif", tile=True, depth="onetile", pyramid=True, compression="jpeg", bigtiff=False)

rows[rows < 200] = 50

vi = pyvips.Image.new_from_array(rows)
vi.tiffsave("./thresholded.tif", tile=True, depth="onetile", pyramid=True, compression="jpeg", bigtiff=False)

100%|██████████| 49/49 [00:00<00:00, 210.52it/s]


overlap_x: 3, overlap_y: 7, patched_image_size: 3577, num_x_patches: 73, num_y_patches: 49
Extracting Patches
Beginning Recombination
New shape: (24752, 37160, 3)


In [3]:
import numpy as np

a = np.array([1,2,3,4])

b = a

a = []

print(b)
print(a)

[1 2 3 4]
[]


In [34]:
g = np.array([1,2,3])

def test(arr):
    print(id(arr))
    arr *= 2
    return arr

b = test(g)

print(g)
print(b)


139676188711152
[2 4 6]
[2 4 6]


In [9]:
None == 0

False

In [10]:
1 + None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [5]:
A = np.array([1,2,3,4])

In [10]:
A[:]

array([], dtype=int64)