In [2]:
from create_patches import patch
import time
from matplotlib import pyplot as plt
import torch
import openslide as op
import numpy as np
# import pyvips

IMAGE_PATH = "../data/new_data/temp/test_images/test_1.svs"
PATCH_PATH = "create_patches"
PATCH_SIZE = 512

patcher = patch.Patcher(PATCH_PATH, use_hdf5=True)# set up the patcher

annotation_mask = op.OpenSlide("../data/new_data/temp/test_masks/test_1_mask.tif")
accept_threshold = 10

# If the filter returns true the patch is removed from the returned patches (assuming return patches is True)
def custom_filter(image, current_patch, anchor, level, patch_size):
    mask_patch = np.array(annotation_mask.read_region((*list(anchor),), level, (patch_size, patch_size)))[:,:,:3]

    if np.mean(mask_patch) > accept_threshold:
        current_patch = current_patch.astype(np.float32) / 1.5
        current_patch[:,:,2] += ((255 - current_patch[:, :, 2]) / 2)
        return True, current_patch.astype(np.uint8)
    else:
        return False, current_patch


patches, metadata = patcher.patch(IMAGE_PATH, PATCH_SIZE, level=0, return_patches=True, filter=custom_filter) # patcher patches the image and saves the patches to and hdf5 file at the path specified to the constuctor
# patcher.patch_with_mask(IMAGE_PATH, XML_PATH, PATCH_SIZE, level=0, return_patches=False, accept_threshold=10) #accept_threshold between 0 and 255


100%|██████████| 49/49 [01:35<00:00,  1.95s/it]


In [3]:
rows = patcher.recombine(patches=patches, metadata=metadata, from_array=True)

Loading array patches
Beginning Recombination
New shape: (24752, 37160, 3)


In [4]:
import pyvips
vi = pyvips.Image.new_from_array(rows)
vi.tiffsave("./recombined_test5.tif", tile=True, depth="onetile", pyramid=True, compression="jpeg", bigtiff=False)

In [1]:
from create_patches import patch
import time
from matplotlib import pyplot as plt
import torch
import pyvips


IMAGE_PATH = "../data/new_data/test_images/test_1.svs"
PATCH_PATH = "create_patches"
PATCH_SIZE = 512


patcher = patch.Patcher(PATCH_PATH) # set up the patcher

patcher.patch(IMAGE_PATH, PATCH_SIZE) # patcher patches the image and saves the patches to and hdf5 file at the path specified to the constuctor

rows = patcher.recombine(IMAGE_PATH)

vi = pyvips.Image.new_from_array(rows)
vi.tiffsave("./normal.tif", tile=True, depth="onetile", pyramid=True, compression="jpeg", bigtiff=False)

rows[rows < 200] = 50

vi = pyvips.Image.new_from_array(rows)
vi.tiffsave("./thresholded.tif", tile=True, depth="onetile", pyramid=True, compression="jpeg", bigtiff=False)

100%|██████████| 49/49 [00:00<00:00, 210.52it/s]


overlap_x: 3, overlap_y: 7, patched_image_size: 3577, num_x_patches: 73, num_y_patches: 49
Extracting Patches
Beginning Recombination
New shape: (24752, 37160, 3)


In [3]:
import numpy as np

a = np.array([1,2,3,4])

b = a

a = []

print(b)
print(a)

[1 2 3 4]
[]


In [34]:
g = np.array([1,2,3])

def test(arr):
    print(id(arr))
    arr *= 2
    return arr

b = test(g)

print(g)
print(b)


139676188711152
[2 4 6]
[2 4 6]
